apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    statefulset: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
          command:
            - sh
            - -c
            - |
              export BROKER_ID=$(echo ${HOSTNAME##*-})
              echo "BROKER_ID=$BROKER_ID"
              export KAFKA_BROKER_ID=$BROKER_ID
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://kafka-${BROKER_ID}.kafka:9092"
              echo "KAFKA_ADVERTISED_LISTENERS=$KAFKA_ADVERTISED_LISTENERS"
              exec /etc/confluent/docker/run


---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: None
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafka

#kubectl exec -it kafka-0 -- kafka-topics --create --topic report --bootstrap-server kafka:9092 --partitions 3 --replication-factor 3

